# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: worker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cworker.proto\x12\x10\x66\x61ultline.worker\"8\n\x10SubmitJobRequest\x12\x0f\n\x07payload\x18\x01 \x01(\t\x12\x13\n\x0btraceparent\x18\x02 \x01(\t\"2\n\x11SubmitJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\"U\n\x13\x43laimNextJobRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x15\n\rlease_seconds\x18\x02 \x01(\x05\x12\x14\n\x0c\x66orce_job_id\x18\x03 \x01(\t\"t\n\x14\x43laimNextJobResponse\x12\x0f\n\x07\x63laimed\x18\x01 \x01(\x08\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\x12\x15\n\rfencing_token\x18\x04 \x01(\x03\x12\x13\n\x0blease_owner\x18\x05 \x01(\t\"N\n\x12\x43ompleteJobRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x15\n\rfencing_token\x18\x03 \x01(\x03\"0\n\x13\x43ompleteJobResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\r\n\x05state\x18\x02 \x01(\t\"\x1f\n\rGetJobRequest\x12\x0e\n\x06job_id\x18\x01 \x01(\t\"[\n\x0eGetJobResponse\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\r\n\x05state\x18\x02 \x01(\t\x12\x13\n\x0blease_owner\x18\x03 \x01(\t\x12\x15\n\rfencing_token\x18\x04 \x01(\x03\x32\xef\x02\n\x0f\x46\x61ultlineWorker\x12T\n\tSubmitJob\x12\".faultline.worker.SubmitJobRequest\x1a#.faultline.worker.SubmitJobResponse\x12]\n\x0c\x43laimNextJob\x12%.faultline.worker.ClaimNextJobRequest\x1a&.faultline.worker.ClaimNextJobResponse\x12Z\n\x0b\x43ompleteJob\x12$.faultline.worker.CompleteJobRequest\x1a%.faultline.worker.CompleteJobResponse\x12K\n\x06GetJob\x12\x1f.faultline.worker.GetJobRequest\x1a .faultline.worker.GetJobResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SUBMITJOBREQUEST']._serialized_start=34
  _globals['_SUBMITJOBREQUEST']._serialized_end=90
  _globals['_SUBMITJOBRESPONSE']._serialized_start=92
  _globals['_SUBMITJOBRESPONSE']._serialized_end=142
  _globals['_CLAIMNEXTJOBREQUEST']._serialized_start=144
  _globals['_CLAIMNEXTJOBREQUEST']._serialized_end=229
  _globals['_CLAIMNEXTJOBRESPONSE']._serialized_start=231
  _globals['_CLAIMNEXTJOBRESPONSE']._serialized_end=347
  _globals['_COMPLETEJOBREQUEST']._serialized_start=349
  _globals['_COMPLETEJOBREQUEST']._serialized_end=427
  _globals['_COMPLETEJOBRESPONSE']._serialized_start=429
  _globals['_COMPLETEJOBRESPONSE']._serialized_end=477
  _globals['_GETJOBREQUEST']._serialized_start=479
  _globals['_GETJOBREQUEST']._serialized_end=510
  _globals['_GETJOBRESPONSE']._serialized_start=512
  _globals['_GETJOBRESPONSE']._serialized_end=603
  _globals['_FAULTLINEWORKER']._serialized_start=606
  _globals['_FAULTLINEWORKER']._serialized_end=973
# @@protoc_insertion_point(module_scope)
