# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: faultline_worker.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'faultline_worker.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16\x66\x61ultline_worker.proto\x12\tfaultline\"5\n\x0c\x43laimRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x12\n\nbatch_size\x18\x02 \x01(\x05\"u\n\nClaimedJob\x12\x0e\n\x06job_id\x18\x01 \x01(\t\x12\x10\n\x08job_type\x18\x02 \x01(\t\x12\x14\n\x0cpayload_json\x18\x03 \x01(\t\x12\x15\n\rfencing_token\x18\x04 \x01(\x03\x12\x18\n\x10lease_expires_at\x18\x05 \x01(\t\"4\n\rClaimResponse\x12#\n\x04jobs\x18\x01 \x03(\x0b\x32\x15.faultline.ClaimedJob\"Q\n\x15StartExecutionRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x15\n\rfencing_token\x18\x03 \x01(\x03\":\n\x16StartExecutionResponse\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"i\n\x18\x43ompleteExecutionRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x15\n\rfencing_token\x18\x03 \x01(\x03\x12\x13\n\x0bresult_json\x18\x04 \x01(\t\">\n\x19\x43ompleteExecutionResponse\x12\x11\n\tcommitted\x18\x01 \x01(\x08\x12\x0e\n\x06reason\x18\x02 \x01(\t\"L\n\x10HeartbeatRequest\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0e\n\x06job_id\x18\x02 \x01(\t\x12\x15\n\rfencing_token\x18\x03 \x01(\x03\"4\n\x11HeartbeatResponse\x12\n\n\x02ok\x18\x01 \x01(\x08\x12\x13\n\x0blease_valid\x18\x02 \x01(\x08\x32\xd7\x02\n\x16\x46\x61ultlineWorkerService\x12>\n\tClaimJobs\x12\x17.faultline.ClaimRequest\x1a\x18.faultline.ClaimResponse\x12U\n\x0eStartExecution\x12 .faultline.StartExecutionRequest\x1a!.faultline.StartExecutionResponse\x12^\n\x11\x43ompleteExecution\x12#.faultline.CompleteExecutionRequest\x1a$.faultline.CompleteExecutionResponse\x12\x46\n\tHeartbeat\x12\x1b.faultline.HeartbeatRequest\x1a\x1c.faultline.HeartbeatResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'faultline_worker_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CLAIMREQUEST']._serialized_start=37
  _globals['_CLAIMREQUEST']._serialized_end=90
  _globals['_CLAIMEDJOB']._serialized_start=92
  _globals['_CLAIMEDJOB']._serialized_end=209
  _globals['_CLAIMRESPONSE']._serialized_start=211
  _globals['_CLAIMRESPONSE']._serialized_end=263
  _globals['_STARTEXECUTIONREQUEST']._serialized_start=265
  _globals['_STARTEXECUTIONREQUEST']._serialized_end=346
  _globals['_STARTEXECUTIONRESPONSE']._serialized_start=348
  _globals['_STARTEXECUTIONRESPONSE']._serialized_end=406
  _globals['_COMPLETEEXECUTIONREQUEST']._serialized_start=408
  _globals['_COMPLETEEXECUTIONREQUEST']._serialized_end=513
  _globals['_COMPLETEEXECUTIONRESPONSE']._serialized_start=515
  _globals['_COMPLETEEXECUTIONRESPONSE']._serialized_end=577
  _globals['_HEARTBEATREQUEST']._serialized_start=579
  _globals['_HEARTBEATREQUEST']._serialized_end=655
  _globals['_HEARTBEATRESPONSE']._serialized_start=657
  _globals['_HEARTBEATRESPONSE']._serialized_end=709
  _globals['_FAULTLINEWORKERSERVICE']._serialized_start=712
  _globals['_FAULTLINEWORKERSERVICE']._serialized_end=1055
# @@protoc_insertion_point(module_scope)
