# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import faultline_worker_pb2 as faultline__worker__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in faultline_worker_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class FaultlineWorkerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ClaimJobs = channel.unary_unary(
                '/faultline.FaultlineWorkerService/ClaimJobs',
                request_serializer=faultline__worker__pb2.ClaimRequest.SerializeToString,
                response_deserializer=faultline__worker__pb2.ClaimResponse.FromString,
                _registered_method=True)
        self.StartExecution = channel.unary_unary(
                '/faultline.FaultlineWorkerService/StartExecution',
                request_serializer=faultline__worker__pb2.StartExecutionRequest.SerializeToString,
                response_deserializer=faultline__worker__pb2.StartExecutionResponse.FromString,
                _registered_method=True)
        self.CompleteExecution = channel.unary_unary(
                '/faultline.FaultlineWorkerService/CompleteExecution',
                request_serializer=faultline__worker__pb2.CompleteExecutionRequest.SerializeToString,
                response_deserializer=faultline__worker__pb2.CompleteExecutionResponse.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/faultline.FaultlineWorkerService/Heartbeat',
                request_serializer=faultline__worker__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=faultline__worker__pb2.HeartbeatResponse.FromString,
                _registered_method=True)


class FaultlineWorkerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def ClaimJobs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CompleteExecution(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaultlineWorkerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ClaimJobs': grpc.unary_unary_rpc_method_handler(
                    servicer.ClaimJobs,
                    request_deserializer=faultline__worker__pb2.ClaimRequest.FromString,
                    response_serializer=faultline__worker__pb2.ClaimResponse.SerializeToString,
            ),
            'StartExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.StartExecution,
                    request_deserializer=faultline__worker__pb2.StartExecutionRequest.FromString,
                    response_serializer=faultline__worker__pb2.StartExecutionResponse.SerializeToString,
            ),
            'CompleteExecution': grpc.unary_unary_rpc_method_handler(
                    servicer.CompleteExecution,
                    request_deserializer=faultline__worker__pb2.CompleteExecutionRequest.FromString,
                    response_serializer=faultline__worker__pb2.CompleteExecutionResponse.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=faultline__worker__pb2.HeartbeatRequest.FromString,
                    response_serializer=faultline__worker__pb2.HeartbeatResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'faultline.FaultlineWorkerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('faultline.FaultlineWorkerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FaultlineWorkerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def ClaimJobs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineWorkerService/ClaimJobs',
            faultline__worker__pb2.ClaimRequest.SerializeToString,
            faultline__worker__pb2.ClaimResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineWorkerService/StartExecution',
            faultline__worker__pb2.StartExecutionRequest.SerializeToString,
            faultline__worker__pb2.StartExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CompleteExecution(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineWorkerService/CompleteExecution',
            faultline__worker__pb2.CompleteExecutionRequest.SerializeToString,
            faultline__worker__pb2.CompleteExecutionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/faultline.FaultlineWorkerService/Heartbeat',
            faultline__worker__pb2.HeartbeatRequest.SerializeToString,
            faultline__worker__pb2.HeartbeatResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
